/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "NeoRust v0.4.2",
  "tagline": "Production-ready Neo N3 blockchain development toolkit built in Rust",
  "favicon": "img/favicon.svg",
  "url": "https://neorust.netlify.app",
  "baseUrl": "/",
  "organizationName": "R3E-Network",
  "projectName": "NeoRust",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/jinghuiliao/git/r3e/NeoRust/website/sidebars.js",
          "editUrl": "https://github.com/R3E-Network/NeoRust/tree/main/website/",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "includeCurrentVersion": true,
          "versions": {
            "current": {
              "label": "v0.4.2",
              "path": ""
            }
          }
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "NeoRust Blog",
          "blogDescription": "Latest updates, tutorials, and insights about NeoRust SDK development",
          "postsPerPage": "ALL",
          "editUrl": "https://github.com/R3E-Network/NeoRust/tree/main/website/"
        },
        "theme": {
          "customCss": "/Users/jinghuiliao/git/r3e/NeoRust/website/src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/neorust-social-card.jpg",
    "metadata": [
      {
        "name": "keywords",
        "content": "neo, blockchain, rust, sdk, neo3, cryptocurrency, smart-contracts, defi"
      },
      {
        "name": "description",
        "content": "NeoRust v0.4.2 - A production-ready Rust SDK for Neo N3 blockchain development. Build high-performance dApps with type-safe, modern Rust. Features 135 passing documentation tests."
      },
      {
        "property": "og:image",
        "content": "https://neorust.netlify.app/img/neorust-social-card.jpg"
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:image",
        "content": "https://neorust.netlify.app/img/neorust-social-card.jpg"
      }
    ],
    "navbar": {
      "title": "NeoRust",
      "logo": {
        "alt": "NeoRust Logo",
        "src": "img/logo-icon.svg",
        "srcDark": "img/logo-icon.svg",
        "width": 32,
        "height": 32
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "📚 Documentation"
        },
        {
          "to": "/examples",
          "label": "💡 Examples",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "🛠️ Tools",
          "position": "left",
          "items": [
            {
              "label": "🦀 Rust SDK",
              "to": "/sdk/intro"
            },
            {
              "label": "🖥️ Desktop GUI",
              "to": "/gui/intro"
            },
            {
              "label": "⌨️ CLI Tools",
              "to": "/cli/intro"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "🔗 Resources",
          "position": "right",
          "items": [
            {
              "label": "📖 API Reference",
              "href": "https://docs.rs/neo3"
            },
            {
              "label": "📦 Crates.io",
              "href": "https://crates.io/crates/neo3"
            },
            {
              "label": "🌐 Neo Developer Portal",
              "href": "https://developers.neo.org/"
            },
            {
              "label": "🔗 Neo X Documentation",
              "href": "https://docs.neox.network/"
            },
            {
              "label": "⭐ GitHub Repository",
              "href": "https://github.com/R3E-Network/NeoRust",
              "className": "dropdown-divider-top"
            }
          ]
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "📚 Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/intro"
            },
            {
              "label": "SDK Documentation",
              "to": "/sdk/intro"
            },
            {
              "label": "GUI Documentation",
              "to": "/gui/intro"
            },
            {
              "label": "CLI Documentation",
              "to": "/cli/intro"
            },
            {
              "label": "Examples",
              "to": "/examples"
            }
          ]
        },
        {
          "title": "🛠️ Tools",
          "items": [
            {
              "label": "Rust SDK",
              "to": "/sdk/installation"
            },
            {
              "label": "Desktop GUI",
              "to": "/gui/installation"
            },
            {
              "label": "CLI Tools",
              "to": "/cli/intro"
            }
          ]
        },
        {
          "title": "🌐 Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/R3E-Network/NeoRust"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/neo-smart-contracts"
            },
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/neo3"
            },
            {
              "label": "Reddit",
              "href": "https://reddit.com/r/NEO"
            }
          ]
        },
        {
          "title": "🔗 More",
          "items": [
            {
              "label": "API Reference",
              "href": "https://docs.rs/neo3"
            },
            {
              "label": "Crates.io",
              "href": "https://crates.io/crates/neo3"
            },
            {
              "label": "Neo Developer Portal",
              "href": "https://developers.neo.org/"
            },
            {
              "label": "Neo X Documentation",
              "href": "https://docs.neox.network/"
            }
          ]
        }
      ],
      "logo": {
        "alt": "NeoRust Logo",
        "src": "img/logo.svg",
        "width": 160,
        "height": 51
      },
      "copyright": "\n          <div style=\"margin-top: 16px; padding-top: 16px; border-top: 1px solid #333;\">\n            <p>Copyright © 2025 R3E Network. Built with ❤️ and Docusaurus.</p>\n            <p>NeoRust v0.4.2 - Production-Ready Neo N3 Development Suite with 135 Passing Doc Tests</p>\n          </div>\n        "
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "rust",
        "toml",
        "bash",
        "json",
        "yaml",
        "typescript",
        "javascript"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "v0.4.2-release",
      "content": "🎉 <strong>NeoRust v0.4.2</strong> is now available! Production-ready with 135 passing documentation tests and enhanced stability. <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/R3E-Network/NeoRust/releases/tag/v0.4.2\">See what's new</a>",
      "backgroundColor": "#059669",
      "textColor": "#ffffff",
      "isCloseable": true
    },
    "algolia": {
      "appId": "BH4D9OD16A",
      "apiKey": "eeb9df8bb56a72c7c37527b60b8cb52c",
      "indexName": "neorust",
      "contextualSearch": true,
      "externalUrlRegex": "external\\.com|domain\\.com",
      "replaceSearchResultPathname": {
        "from": "/docs/",
        "to": "/"
      },
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "sdk",
        "path": "sdk",
        "routeBasePath": "sdk",
        "sidebarPath": "/Users/jinghuiliao/git/r3e/NeoRust/website/sidebars-sdk.js",
        "editUrl": "https://github.com/R3E-Network/NeoRust/tree/main/website/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "gui",
        "path": "gui",
        "routeBasePath": "gui",
        "sidebarPath": "/Users/jinghuiliao/git/r3e/NeoRust/website/sidebars-gui.js",
        "editUrl": "https://github.com/R3E-Network/NeoRust/tree/main/website/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "cli",
        "path": "cli",
        "routeBasePath": "cli",
        "sidebarPath": "/Users/jinghuiliao/git/r3e/NeoRust/website/sidebars-cli.js",
        "editUrl": "https://github.com/R3E-Network/NeoRust/tree/main/website/",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true
      }
    ]
  ],
  "headTags": [
    {
      "tagName": "link",
      "attributes": {
        "rel": "preconnect",
        "href": "https://fonts.googleapis.com"
      }
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "preconnect",
        "href": "https://fonts.gstatic.com",
        "crossorigin": "anonymous"
      }
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "stylesheet",
        "href": "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap"
      }
    }
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
